name: Test Coverage Check

on:
  push:
    branches: ["develop", "main"]
    paths: ['**.java', '.github/workflows/jacoco.yml', pom.xml']
  pull_request:
    branches: ["develop", "main"]
  workflow_dispatch:
  
jobs:
  jacoco-java-maven:
    
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    
    - name: Build with Maven
      run: mvn -B test --file pom.xml -Pcoverage
      
    - name: Generate Jacoco badge
      id: jacoco
      uses: cicirello/jacoco-badge-generator@v2.8.1
      with:
        jacoco-csv-file: target/site/jacoco/jacoco.csv
        badges-directory: badges
        generate-coverage-badge: true
        coverage-badge-filename: jacoco.svg
        generate-branches-badge: true
        branches-badge-filename: branches.svg
        generate-summary: true
        summary-filename: coverage-summary.json
        coverage-label: coverage
        branches-label: branches
        colors: '#4c1 #97ca00 #a4a61d #dfb317 #fe7d37 #e05d44'
        intervals: 100 90 80 70 60 0
        on-missing-report: fail
        fail-if-coverage-less-than: 55
        fail-if-branches-less-than: 55
        fail-on-coverage-decrease: false
        fail-on-branches-decrease: false
        
    - name: Log Coverage percentage to Workflow output
      run: |
        echo "Coverage = ${{ steps.jacoco.output.coverage}}
        echo "Branch Coverage = ${{ steps.jacoco.output.branches}}
        
    - name: Upload Jacoco coverage report as workflow artifact
      uses: actions/upload-artifact@v3
      with:
        name: jacoco-report
        path: target/site/jacoco
        
    - name: Comment on PR with Coverage
      if: ${{github.event_name == 'pull_request'}}
      run: |
        REPORT=$(<badges/coverage-summary.json)
        COVERAGE=$(jq -r '.coverage' <<< "$REPORT")%
        BRANCHES=$(jq -r '.branches' <<< "$REPORT")%
        NEWLINE=$'\n'
        BODY="## JaCoCo Test Coverage Summary Statistics${NEWLINE}* __Coverage:__ ${COVERAGE}${NEWLINE}* __Branches:__ ${BRANCHES}"
        gh pr comment ${{github.event.pull_request.number}} -b "${BODY}"
      continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
        
    - name: Commit and push the coverage badges and summary file
      if: ${{ github.event_name != 'pull_request' }}
      run: |
        cd badges
        if [[ `git status --porcelain *.svg *.json` ]]; then
          git config --global user.name 'github-actions'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add *.svg *.json
          git commit -m "Autogenerated JaCoCo coverage badges" *.svg *.json
          git push
        fi
        
    - name: Get Coverage Info
      run: | 
        echo "Total Coverage ${{ steps.jacoco.outputs.coverage-overall }} "
        echo "Changed Files Coverage ${{ steps.jacoco.outputs.coverage-changed-files }}"
        
